version: '3.9'
services:
  node_app:
    container_name: node_app
    build: .
    image: node_app
    entrypoint: "dockerize -wait tcp://db:3306 -timeout 20s /usr/local/bin/docker-entrypoint.sh"
    command: "node ./server.js"
    tty: true
    depends_on:
      - db

  db:
    image: mysql
    container_name: db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: names_db
      MYSQL_ROOT_PASSWORD: root

  nginx:
    container_name: nginx
    image: nginx
    ports:
      - '8080:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - node_app
